version: '2.4'
services:
  task:
    image: task
    privileged: true
    build: 
      context: ../../
      dockerfile: src/task/dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../src/task:/root/task
      - ../../config:/root/config
      - "../../data/datasets:/root/task/datasets:rw"
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - DATASET=${DATASET}
    command: bash -c "source catkin_ws/devel/setup.bash;
                      rosparam load /root/config/${CONFIG} /pose_estimator;
                      python /root/task/test_obj_det_dev.py"
    stdin_open: true
    tty: true