version: '2.4'
services:
  gdrnpp:
    image: gdrnpp
    build:
      context: ../../src/gdrnpp_bop2022/docker
      dockerfile: dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - "../../src/gdrnpp_bop2022:/root/gdrnpp:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - "../../data/weights/gdrnpp:/root/gdrnpp/output:rw"
      - "../../data/datasets:/root/gdrnpp/datasets/BOP_DATASETS:rw"
      - ../../config:/root/config
    environment: 
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - DATASET=${DATASET}
    command: bash -c "source catkin_ws/devel/setup.bash;
             python ./gdrnpp/core/gdrn_modeling/demo/demo_gdrn_ros_robokudo.py --model_file ${DATASET}"        
    stdin_open: true
    tty: true
